# Generated by Django 3.2.4 on 2021-06-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='~/projects/shop/shop/static/no-image.png', upload_to='', verbose_name='Изображение'),
        ),
    ]
