# Generated by Django 3.0.8 on 2021-11-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20211101_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='favorities',
            field=models.ManyToManyField(related_name='related_customer', to='mainapp.Product', verbose_name='Избранное'),
        ),
    ]
