# Generated by Django 3.0.8 on 2021-11-01 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20211101_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='favorities',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('favorities', models.ManyToManyField(related_name='related_customer', to='mainapp.Product', verbose_name='Избранное')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Customer')),
            ],
        ),
    ]
