# Generated by Django 3.0.8 on 2021-11-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20211101_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='favorities',
            field=models.ManyToManyField(related_name='related_customer', to='mainapp.Product', verbose_name='Избранное'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
